-- Fixture de TESTE: reproduz as colunas das tabelas vne_* de producao (dump de 22/09/2026).
-- Usado apenas em bancos descartaveis (embedded-postgres). Nunca aplicar em producao.
CREATE TABLE vne_leads_snapshot (
  lead_id bigint PRIMARY KEY, lead_name text, pipeline_id bigint, status_id bigint, responsible_user_id bigint,
  price numeric, loss_reason_id bigint, created_at_kommo timestamptz, updated_at_kommo timestamptz,
  first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, last_status_change_at timestamptz,
  last_responsible_change_at timestamptz, last_message_client_at timestamptz, last_message_company_at timestamptz,
  total_incoming int NOT NULL DEFAULT 0, total_outgoing int NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}',
  is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz, restored_at timestamptz
);
CREATE TABLE vne_mensagens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kommo_message_id text, lead_id bigint, contact_id bigint,
  talk_id text, chat_id text, direcao text NOT NULL, tipo_autor text, author_user_id text, author_name text,
  texto text, message_type text, attachment_type text, attachment_link text, attachment_file_name text, origin text,
  created_at_kommo timestamptz, received_at timestamptz NOT NULL DEFAULT now(), metadata jsonb NOT NULL DEFAULT '{}',
  autor_classificacao text, workflow_origem text, is_automated boolean, delivery_status text
);
CREATE INDEX idx_vne_mensagens_lead_created ON vne_mensagens (lead_id, created_at_kommo DESC);
CREATE TABLE vne_eventos_crm (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_key text UNIQUE, source text NOT NULL,
  event_type text NOT NULL, entity_type text NOT NULL, entity_id bigint, lead_id bigint, contact_id bigint,
  pipeline_id bigint, status_id bigint, previous_pipeline_id bigint, previous_status_id bigint,
  responsible_user_id bigint, modified_user_id bigint, occurred_at timestamptz, received_at timestamptz NOT NULL DEFAULT now(),
  payload jsonb NOT NULL DEFAULT '{}', task_id bigint, task_type_id bigint, task_status int, task_text text,
  task_complete_till timestamptz, task_result text, talk_id text, chat_id text, talk_is_in_work boolean, talk_is_read boolean
);
CREATE INDEX idx_vne_eventos_lead ON vne_eventos_crm (lead_id, occurred_at DESC);
CREATE TABLE vne_chat_map (
  talk_id text PRIMARY KEY, lead_id bigint, contact_id bigint, chat_id text, origin text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE vne_janela_meta (
  lead_id bigint PRIMARY KEY, contact_id bigint, chat_id text, origin text, contact_name text,
  ultima_mensagem_cliente_em timestamptz NOT NULL, ultimo_workflow text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
